# Generated by Django 5.0.1 on 2025-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='concertdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concertname', models.CharField(max_length=20)),
                ('concertdate', models.DateField()),
                ('concerttime', models.TimeField()),
                ('concertvenue', models.CharField(max_length=20)),
                ('ticketprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availabletickets', models.IntegerField()),
            ],
        ),
    ]
