# Generated by Django 5.0.1 on 2025-02-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_concertdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('concertname', models.CharField(max_length=20)),
                ('ticketprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookedtickets', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
